force-app/main/default/objects/Product2/fields/GTIN__c.field-meta.xml
<CustomField>
    <fullName>GTIN__c</fullName>
    <label>GTIN</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Staging_Product__c/Staging_Product__c.object-meta.xml
<CustomObject>
    <label>Staging Product</label>
    <nameField>
        <label>Staging Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staging_Product__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>TODAY() - DATEVALUE(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age (in days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staging_Product__c/fields/GTIN__c.field-meta.xml
<CustomField>
    <fullName>GTIN__c</fullName>
    <label>GTIN</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductDetailController.cls
public with sharing class ProductDetailController {

    @AuraEnabled(cacheable=true)
    public static List<Staging_Product__c> getStagingProductDetails(String productId) {
        List<Product2> productList = [SELECT GTIN__c FROM Product2 WHERE Id = :productId];
        if(productList != null && productList.size() > 0) {
            return [SELECT Id,Name, GTIN__c, Age__c FROM Staging_Product__c WHERE GTIN__c = :[SELECT GTIN__c FROM Product2 WHERE Id = :productId].GTIN__c];
        }
        return new List<Staging_Product__c>();
    }
}