force-app/main/default/objects/Product2/fields/GTIN__c.field-meta.xml
<CustomField>
    <fullName>GTIN__c</fullName>
    <label>GTIN</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Purchasing_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchasing_Price__c</fullName>
    <label>Purchasing Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staging_Product__c/Staging_Product__c.object-meta.xml
<CustomObject>
    <label>Staging Product</label>
    <nameField>
        <label>Staging Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staging_Product__c/fields/GTIN__c.field-meta.xml
<CustomField>
    <fullName>GTIN__c</fullName>
    <label>GTIN</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Product__c/fields/Purchasing_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchasing_Price__c</fullName>
    <label>Purchasing Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staging_Product__c/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProductDetailControllerTest.cls
@isTest
public inherited sharing class ProductDetailControllerTest {
    
    @TestSetup
    static void makeData(){
        Staging_Product__c stagingProduct = new Staging_Product__c();
        stagingProduct.Name = 'TestProduct-1';
        stagingProduct.GTIN__c = SObjectUtils.generateRandomString();
        stagingProduct.Purchasing_Price__c = 150;
        stagingProduct.Selling_Price__c = 170;
        insert stagingProduct;
    }

    @isTest
    static void getProductFromStagingProduct_Positive() {
        Product2 p = [SELECT Id, GTIN__c FROM Product2 LIMIT 1][0];
        Test.startTest();
        List<Staging_Product__c> spList = ProductDetailController.getStagingProductDetails(p.Id);
        Test.stopTest();

        System.assertEquals(spList.size(), 1, 'There should be one element in the list.');
        System.assertEquals(spList[0].GTIN__c, p.GTIN__c, 'GTIN__c values should be the same.');
    }

    @isTest
    static void getProductFromStagingProduct_Negative() {
        Test.startTest();
        List<Staging_Product__c> spList = ProductDetailController.getStagingProductDetails(null);
        Test.stopTest();

        System.assertEquals(spList.size(), 0, 'There should be no elements in the list.');
    }
}