force-app/main/default/objects/Staging_Product__c/Staging_Product__c.object-meta.xml
<CustomObject>
    <label>Staging Product</label>
    <nameField>
        <label>Staging Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staging_Product__c/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmailHandler.cls
public with sharing class EmailHandler {
    
    /**
     * notifyCommercialDirector                 Informs the User with Role 'Commercial Director' about all the products whose Selling_Price__c has changed by more than 10%
     * @param  priceSensitiveProductsNewValues  Map<Id,Staging_Product__c>
     * @param  priceSensitiveProductsOldValues  Map<Id,Staging_Product__c>
     * @return 'void'
     */
    public static void notifyCommercialDirector(Map<Id,Staging_Product__c> priceSensitiveProductsNewValues, Map<Id,Staging_Product__c> priceSensitiveProductsOldValues) {
        User commercialDirector = [
            SELECT Email
            FROM User 
            WHERE UserRoleId = :[SELECT Id FROM UserRole WHERE Name = 'Mr. Commercial Director' LIMIT 1].Id
            LIMIT 1
        ];
        if(commercialDirector != null) {
            Messaging.reserveSingleEmailCapacity(2);    
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(
                new List<String> {commercialDirector.Email}
            );
            mail.setSubject(System.Label.Price_Sensitivity_Subject);
            List<String> changedValues = new List<String>();
            for(Staging_Product__c sp: priceSensitiveProductsNewValues.values()) {
                changedValues.add(
                    '<a href="'+ URL.getSalesforceBaseUrl().toExternalForm() + '/' + sp.Id +'">' + sp.Name +'</a>' + ' - ' + '[NEW]: ' + sp.Selling_Price__c + ' | [OLD]: ' + priceSensitiveProductsOldValues.get(sp.Id).Selling_Price__c + '<br>'
                );
            }
            mail.setHtmlBody(
                '<html>' + System.Label.Price_Sensitivity_Body + '<br><br>' + String.join(changedValues, ',') + '</html>'
            );
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}